copy /y theme.xml 3do
copy /y theme.xml ags
copy /y theme.xml amiga
copy /y theme.xml amstradcpc
copy /y theme.xml apple2
copy /y theme.xml arcade
copy /y theme.xml atari800
copy /y theme.xml atari2600
copy /y theme.xml atari5200
copy /y theme.xml atari7800
copy /y theme.xml atarijaguar
copy /y theme.xml atarilynx
copy /y theme.xml atarist
copy /y theme.xml bbcmicro
copy /y theme.xml c64
copy /y theme.xml channelf
copy /y theme.xml coco
copy /y theme.xml colecovision
copy /y theme.xml daphne
copy /y theme.xml desktop
copy /y theme.xml dragon32
copy /y theme.xml dreamcast
copy /y theme.xml fba
copy /y theme.xml fds
copy /y theme.xml gameandwatch
copy /y theme.xml gamegear
copy /y theme.xml gb
copy /y theme.xml gba
copy /y theme.xml gbc
copy /y theme.xml gc
copy /y theme.xml genesis
copy /y theme.xml intellivision
copy /y theme.xml kodi
copy /y theme.xml love
copy /y theme.xml macintosh
copy /y theme.xml mame
copy /y theme.xml mame-advmame
copy /y theme.xml mame-libretro
copy /y theme.xml mame-mame4all
copy /y theme.xml mastersystem
copy /y theme.xml megadrive
copy /y theme.xml mess
copy /y theme.xml misc
copy /y theme.xml msx
copy /y theme.xml n64
copy /y theme.xml nds
copy /y theme.xml neogeo
copy /y theme.xml nes
copy /y theme.xml ngp
copy /y theme.xml ngpc
copy /y theme.xml odyssey2
copy /y theme.xml oric
copy /y theme.xml pc
copy /y theme.xml pce-cd
copy /y theme.xml pcengine
copy /y theme.xml ports
copy /y theme.xml ps2
copy /y theme.xml psp
copy /y theme.xml psx
copy /y theme.xml residualvm
copy /y theme.xml samcoupe
copy /y theme.xml saturn
copy /y theme.xml scummvm
copy /y theme.xml sega32x
copy /y theme.xml segacd
copy /y theme.xml sg-1000
copy /y theme.xml smw
copy /y theme.xml snes
copy /y theme.xml steam
copy /y theme.xml stratagus
copy /y theme.xml supergrafx
copy /y theme.xml tg16
copy /y theme.xml tg-cd
copy /y theme.xml ti99
copy /y theme.xml trs80
copy /y theme.xml vectrex
copy /y theme.xml videopac
copy /y theme.xml virtualboy
copy /y theme.xml wii
copy /y theme.xml wonderswan
copy /y theme.xml wonderswancolor
copy /y theme.xml zmachine
copy /y theme.xml zxspectrum
copy /y theme.xml x68000